//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFRepository
{
	using Contracts;
	using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRegistrationHistory : PersistableModel<DeliveryRegistrationHistory>
	{
        public long Id { get; set; }
        public string CIF { get; set; }
        public string ECRN { get; set; }
        public string CRNN { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string AcountNumber { get; set; }
        public string CreditCardNumber { get; set; }
        public string DeliveryMode { get; set; }
        public string MobileNumber { get; set; }
        public string FaxNumber { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public Nullable<bool> SubForAccount { get; set; }
        public Nullable<bool> SubForCreditCard { get; set; }
        public Nullable<bool> SubForRemittance { get; set; }
        public Nullable<bool> SubForDeposit { get; set; }
        public Nullable<bool> SubForJointAccount { get; set; }
        public Nullable<bool> SubForInv { get; set; }
        public Nullable<bool> SubForTF { get; set; }
        public string MakerId { get; set; }
        public string CheckerId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastModifictionDate { get; set; }
        public string ApprovalStatus { get; set; }
        public string ModeOfRegistration { get; set; }
        public string MasterNumber { get; set; }
        public Nullable<long> ModificationId { get; set; }
        public int Modifications { get; set; }
        public string RequestStatus { get; set; }
        public string Comments { get; set; }
        public int ActionCode { get; set; }
        public System.DateTime HistoryDateTime { get; set; }
    }
}
