//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailModification
    {
        public int Id { get; set; }
        public long DetailsId { get; set; }
        public System.DateTime ModificationDate { get; set; }
        public string AgentId { get; set; }
        public string FieldModified { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
    
        public virtual DeliveryRegistrationDetail DeliveryRegistrationDetail { get; set; }
    }
}
