//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        public int Id { get; set; }
        public string URL { get; set; }
        public bool IsUpload { get; set; }
    }
}
