//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumBanking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PremiumBanking()
        {
            this.PremiumModifications = new HashSet<PremiumModification>();
        }
    
        public int Id { get; set; }
        public string CIFID { get; set; }
        public string PremiumCustomer { get; set; }
        public string CustomerClassification { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastModificationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PremiumModification> PremiumModifications { get; set; }
    }
}
