//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessedFile
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string FileName { get; set; }
        public string MD5Hash { get; set; }
    }
}
